### ISSUE TITLE
Import fails 

### ISSUE THREAD

**Issue by splitbrain** [dokuwiki/translate.dokuwiki.org#120]
Currently the import of the gallery plugin fails:

```
19:30:02 ERROR     [app] Error during repository update (App\Services\Git\GitPullException: Failed to pull https://github.com/splitbrain/dokuwiki-plugin-gallery.git/master
Path: /var/www/translate/data/plugin/gallery/repository/
Command: /usr/bin/git pull -f https://github.com/splitbrain/dokuwiki-plugin-gallery.git master
Return : 128
STDOUT :
STDERR : error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
)
19:30:02 WARNING   [php] Warning: file_get_contents(https://kctbh9vrtdwd.statuspage.io/api/v2/summary.json): failed to open stream: HTTP request failed! HTTP/1.1 426 Upgrade Required
 ["exception" => ErrorException { …}]
```

I suspect this problem might happen when a force push happens at the upstream repository? Maybe instead of pulling a `reset --hard origin <branch>` would be the better approach?

BTW. I am not sure the warning is related the error above. It might be something else?

**Comment by Klap-in** [comment]
I'm unsure if just a force push on upstream is the cause. There should also something that let it deviates such that it create conflicts.

Before reading your proposal, it tried `git reset --hard`, which seems to work for this and another plugin. 
With a bit reading I understand what you propose. 

git pull includes a fetch from remote.

So if I understand it right, then the following two commands fetch only the desired branch from the plugin authors (remote) repository. And resets git, such that all existing changes are discarded. With FETCH_HEAD we do not to set the authors repository as upstream remote.

> _git reset --hard docs:_  Resets the index and working tree. Any changes to tracked files in the working tree since <commit> are discarded. Any untracked files or directories in the way of writing any tracked files are simply deleted.

Normally we do make changes on the server in the `repository/` folder, if we would do `git clean -f` could be considered. But better no manually changes are made in that folder.

```
git fetch https://github.com/splitbrain/dokuwiki-plugin-gallery.git master
git reset --hard FETCH_HEAD
```
As this deviates the local checkout from the remote origin (our fork on github/gitlab), we need to do forced push to update the remote origin, which we do already. So that should work fine as well.

Do you see this issues with this approach? Otherwise I will try to implement it.

**Comment by splitbrain** [comment]
Yeah, seems reasonable. Basically we should always take the upstream repo as gospel. If our version differs, the we should consider our version wrong.

**Comment by Klap-in** [comment]
Yeah, I agree.

The tool tried to be smart by checking the output of a pull is 'Already up-to-date' to prevent unnecessary language parsing and updating. New trick needed with the reset.
 
```
translate@piggy:~/data/plugin/sqlite/repository$ git reset --hard FETCH_HEAD 
HEAD is now at 6cb8d74 Version upped
```
Now trying to compare `.git/FETCH_HEAD` before and after the fetch. Seems to do the job.
